### ISSUE TITLE
App fails to start because @medplum/core and @medplum/react cannot be resolved

### ISSUE THREAD

**Issue by Bluejay123** [medplum/medplum-provider#1]
**Expected**: `npm run dev` should start the app in localhost correctly
**Actual**:  Failed to resolve import "@medplum/core" from "src/main.tsx". Does the file exist?

**Root cause**: 
In vite.config.ts, @medplum/core is linked to the wrong location:
```
export default defineConfig({
...
  resolve: {
    alias: {
      '@medplum/core': path.resolve(__dirname, '../../packages/core/src'),
      '@medplum/react': path.resolve(__dirname, '../../packages/react/src'),
    },
  },
});
```

**Proposed solution**: remove the alias lines

**Comment by niccoreyes** [comment]
I deleted those lines since it was a bit sus when the libraries have to be declared in a different path way different from the node_modules structure on my investigation.

The @medplum/core is installed in the correct default location on npm install and there is no need to redirect the path. 
Maybe this would apply in environments where the libraries are shared by a patient and provider setup in a different parent path.
